#!/usr/bin/env python
# -*- coding: utf-8 -*-

#=============================================
# 함께 사용되는 각종 파이썬 패키지들의 import 선언부
#=============================================
import numpy as np
import cv2
import rospy, time
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from xycar_msgs.msg import xycar_motor
from math import *
import signal
import sys
import os

#=============================================
# 터미널에서 Ctrl-c 키입력이로 프로그램 실행을 끝낼 때
# 그 처리시간을 줄이기 위한 함수
#=============================================
def signal_handler(sig, frame):
    time.sleep(3)
    os.system('killall -9 python rosout')
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

#=============================================
# 프로그램에서 사용할 변수, 저장공간 선언부
#=============================================
image = np.empty(shape=[0]) # 카메라 이미지를 담을 변수
bridge = CvBridge()
motor = None # 모터 토픽을 담을 변수

#=============================================
# 프로그램에서 사용할 상수 선언부
#=============================================
CAM_FPS = 30    # 카메라 FPS - 초당 30장의 사진을 보냄
WIDTH, HEIGHT = 640, 480    # 카메라 이미지 가로x세로 크기
#=====================
warp_Offset = 120

# 트랙 동영상 읽어 들이기
window_title = 'camera'
window_title2 = 'camera2'

warp_img_w = 320
warp_img_h = 240

# 슬라이딩 윈도우 개수
nwindows = 9
# 슬라이딩 윈도우 넓이
margin = 12
# 선을 그리기 위해 최소한 있어야 할 점의 개수
minpix = 5

lane_bin_th = 145

warp_src  = np.array([
    [100, 300],  
    [0, 480],
    [WIDTH - 100, 300],
    [WIDTH, 480]
], dtype=np.float32)

warp_dist = np.array([
    [0,0],
    [0,warp_img_h],
    [warp_img_w,0],
    [warp_img_w, warp_img_h]
], dtype=np.float32)


# 변환전과 후의 4개 점 좌표를 전댈해서 이미지를 원근변환 처리하여 새로운 이미지로 만들기
def warp_image(img, src, dst, size):
    M = cv2.getPerspectiveTransform(src, dst)
    Minv = cv2.getPerspectiveTransform(dst, src)
    warp_img = cv2.warpPerspective(img, M, size, flags=cv2.INTER_LINEAR)

    return warp_img, M, Minv

#=============================================
# 콜백함수 - 카메라 토픽을 처리하는 콜백함수
# 카메라 이미지 토픽이 도착하면 자동으로 호출되는 함수
# 토픽에서 이미지 정보를 꺼내 image 변수에 옮겨 담음.
#=============================================
def img_callback(data):
    global image
    image = bridge.imgmsg_to_cv2(data, "bgr8")

#=============================================
# 모터 토픽을 발행하는 함수
# 입력으로 받은 angle과 speed 값을
# 모터 토픽에 옮겨 담은 후에 토픽을 발행함.
#=============================================
def drive(angle, speed):

    global motor

    motor_msg = xycar_motor()
    motor_msg.angle = angle
    motor_msg.speed = speed

    motor.publish(motor_msg)

#=============================================
# 실질적인 메인 함수
# 카메라 토픽을 받아 각종 영상처리와 알고리즘을 통해
# 차선의 위치를 파악한 후에 조향각을 결정하고,
# 최종적으로 모터 토픽을 발행하는 일을 수행함.
#=============================================
def start():

    # 위에서 선언한 변수를 start() 안에서 사용하고자 함
    global motor, image

    #=========================================
    # ROS 노드를 생성하고 초기화 함.
    # 카메라 토픽을 구독하고 모터 토픽을 발행할 것임을 선언
    #=========================================
    rospy.init_node('driving')
    motor = rospy.Publisher('xycar_motor', xycar_motor, queue_size=1)
    rospy.Subscriber("/usb_cam/image_raw/",Image, img_callback)

    print ("----- Xycar self driving -----")

    # 첫번째 카메라 토픽이 도착할 때까지 기다림.
    rospy.wait_for_message("/usb_cam/image_raw/", Image)

    #=========================================
    # 메인 루프
    # 카메라 토픽이 도착하는 주기에 맞춰 한번씩 루프를 돌면서
    # "이미지처리 + 차선위치찾기 + 조향각 결정 + 모터토픽 발행"
    # 작업을 반복적으로 수행함.
    #=========================================
    while not rospy.is_shutdown():

        # 이미지 처리를 위해 카메라 원본 이미지를 img에 복사 저장한다.
        img = image.copy()

        warp_img, M, Minv = warp_image(img, warp_src, warp_dist, (warp_img_w, warp_img_h))
        
	green_color = (0,0,255)
	points1 = np.array([[101, 0], [221, 0], [350, 245], [0, 245]], dtype=np.int32)
	rec = cv2.fillConvexPoly(warp_img,points1,green_color)

	lower_white = np.array([200, 200, 200], dtype=np.uint8)
	upper_white = np.array([255, 255, 255], dtype=np.uint8)
	white_mask = cv2.inRange(rec, lower_white, upper_white)

	binary = cv2.threshold(white_mask, 128, 255, cv2.THRESH_BINARY)[1]


	
   
	#480 640
	#280 180
	#green_color = (0,255,0)
	#points1 = np.array([[10, 10], [800, 10], [800, 270], [10, 270]], dtype=np.int32)
	#rec = cv2.fillConvexPoly(img,points1,green_color)

	#hsv1 = cv2.cvtColor(rec,cv2.COLOR_BGR2HSV)
        #lowerb1 = (100,70,50)
        #upperb1 = (110,255,100)
        #inRange_1 = cv2.inRange(hsv1,lowerb1,upperb1)

	#hsv2 = cv2.cvtColor(rec,cv2.BGR)

        # img를 화면에 출력한다.
        cv2.imshow("CAM View", img)
	cv2.imshow(window_title, warp_img)
        #cv2.imshow("inRange", inRange_1)
	cv2.imshow("rec", rec)
	cv2.imshow('White Extraction', binary)
        cv2.waitKey(1)

        #=========================================
        # 핸들 조향각 값인 angle값 정하기.
        # 차선의 위치 정보를 이용해서 angle값을 설정함.
        #=========================================

        # 핸들을 얼마나 꺾을지 결정
        angle = 0

        #=========================================
        # 차량의 속도 값인 speed값 정하기.
        # 주행 속도를 조절하기 위해 speed값을 설정함.
        #=========================================

        # 주행 속도를 결정
        speed = 10

        # drive() 호출. drive()함수 안에서 모터 토픽이 발행됨.
        drive(angle, speed)


#=============================================
# 메인 함수
# 가장 먼저 호출되는 함수로 여기서 start() 함수를 호출함
# start() 함수가 실질적인 메인 함수임.
#=============================================
if __name__ == '__main__':
    start()

